use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{Context, Result};

/// Detect which prose formats exist in the current directory tree.
fn detect_formats(dir: &Path) -> Vec<&'static str> {
    let mut formats = Vec::new();
    let check = |ext: &str| -> bool {
        walkdir(dir)
            .into_iter()
            .any(|e| e.path().extension().and_then(|e| e.to_str()) == Some(ext))
    };
    // Simple recursive check using std::fs
    fn walkdir(dir: &Path) -> Vec<fs::DirEntry> {
        let mut entries = Vec::new();
        if let Ok(rd) = fs::read_dir(dir) {
            for entry in rd.flatten() {
                let path = entry.path();
                if path.is_dir()
                    && !path
                        .file_name()
                        .is_some_and(|n| n.to_string_lossy().starts_with('.'))
                {
                    entries.extend(walkdir(&path));
                } else {
                    entries.push(entry);
                }
            }
        }
        entries
    }

    if check("org") {
        formats.push("org");
    }
    if check("tex") || check("latex") {
        formats.push("latex");
    }
    if check("md") || check("markdown") {
        formats.push("markdown");
    }
    formats
}

/// Generate .snapperrc.toml content.
fn generate_config(formats: &[&str]) -> String {
    let default_format = formats.first().copied().unwrap_or("plaintext");
    format!(
        r##"# snapper project configuration
# https://snapper.turtletech.us/docs/reference/config/

# Extra abbreviations (merged with built-in list)
# extra_abbreviations = ["GROMACS", "LAMMPS", "DFT"]

# File patterns to ignore
# ignore = ["*.bib", "*.cls", "*.sty"]

# Default format (auto-detected from extension if omitted)
format = "{default_format}"

# Maximum line width (0 = unlimited)
max_width = 0

# Prefer breaks after independent-clause punctuation (, ; : em dash).
# With max_width = 0 this still inserts a newline after each such mark
# that is already followed by whitespace.
# clause_breaks = false

# Extra LaTeX environments / commands (added to the built-in lists).
# [latex]
# verbatim_envs = ["Verbatim"]
# structure_envs = ["algorithm", "comment"]
# verbatim_commands = ["Verb"]

# Advisory long-line threshold when max_width is 0 (default 120)
# long_threshold = 120

# Per-language code-block reflow and formatter delegation.
# Each language entry may set any combination of:
#   line_comment   -- marker for single-line comments
#   block_comment  -- ["open", "close"] markers for multi-line comments
#   formatter      -- argv passed to std::process::Command for --format-code
# Missing fields are no-ops for that language.

[code.rust]
line_comment = "//"
block_comment = ["/*", "*/"]
formatter = ["rustfmt", "--edition", "2024"]

[code.python]
line_comment = "#"
block_comment = ["\"\"\"", "\"\"\""]
formatter = ["ruff", "format", "-"]

[code.toml]
line_comment = "#"
formatter = ["taplo", "format", "-"]

[code.lua]
line_comment = "--"
block_comment = ["--[[", "]]"]

[code.lisp]
line_comment = ";"

[code.html]
block_comment = ["<!--", "-->"]

[code.javascript]
line_comment = "//"
block_comment = ["/*", "*/"]
formatter = ["prettier", "--stdin-filepath", "src.js"]
"##
    )
}

/// Generate .gitattributes entries.
fn generate_gitattributes(formats: &[&str]) -> String {
    let mut lines = String::from("# snapper semantic line break filter\n");
    for fmt in formats {
        let ext = match *fmt {
            "org" => "*.org",
            "latex" => "*.tex",
            "markdown" => "*.md",
            _ => continue,
        };
        lines.push_str(&format!("{ext} filter=snapper\n"));
    }
    lines
}

/// Generate pre-commit config snippet.
fn generate_precommit() -> String {
    format!(
        r#"# Add to .pre-commit-config.yaml:
- repo: https://github.com/TurtleTech-ehf/snapper
  rev: v{}
  hooks:
    - id: snapper
"#,
        env!("CARGO_PKG_VERSION")
    )
}

const HOOK_MARKER: &str = "Generated by `snapper init`";

/// Git pre-commit hook that formats staged prose with native parsers.
fn generate_precommit_hook() -> String {
    format!(
        r#"#!/usr/bin/env bash
# {HOOK_MARKER}. Format staged prose with native parsers.
# bash, not /bin/sh: NUL-delimited `read -d ''` is not POSIX, and
# Ubuntu's dash skips the loop.
set -e
# Prefer snapper-fmt: argv0 snapper collides with openSUSE's Btrfs tool.
if command -v snapper-fmt >/dev/null 2>&1; then
  SNAPPER=snapper-fmt
elif command -v snapper >/dev/null 2>&1; then
  SNAPPER=snapper
else
  echo "snapper: neither snapper-fmt nor snapper on PATH; skip" >&2
  exit 0
fi

git diff --cached --name-only --diff-filter=ACM -z |
while IFS= read -r -d '' f || [ -n "$f" ]; do
  case "$f" in
    *.org|*.tex|*.latex|*.md|*.markdown|*.rst|*.txt)
      "$SNAPPER" --native --in-place -- "$f"
      git -c filter.snapper.clean=cat add -- "$f"
      ;;
  esac
done
"#
    )
}

fn git_hooks_dir(cwd: &Path) -> Option<PathBuf> {
    let output = Command::new("git")
        .args(["rev-parse", "--git-path", "hooks"])
        .current_dir(cwd)
        .output()
        .ok()?;
    if !output.status.success() {
        return None;
    }
    let rel = String::from_utf8_lossy(&output.stdout);
    let rel = rel.trim();
    if rel.is_empty() {
        return None;
    }
    let path = Path::new(rel);
    Some(if path.is_absolute() {
        path.to_path_buf()
    } else {
        cwd.join(path)
    })
}

fn write_precommit_hook(cwd: &Path, dry_run: bool) -> Result<()> {
    let Some(hooks_dir) = git_hooks_dir(cwd) else {
        eprintln!("  not a git repository; skip pre-commit hook");
        return Ok(());
    };
    let hook_path = hooks_dir.join("pre-commit");
    let content = generate_precommit_hook();
    if dry_run {
        eprintln!("\n--- {} ---", hook_path.display());
        eprint!("{content}");
        return Ok(());
    }
    if hook_path.exists() {
        let existing = fs::read_to_string(&hook_path).unwrap_or_default();
        if !existing.contains(HOOK_MARKER) {
            eprintln!(
                "  {} already exists and is not a snapper hook, skipping",
                hook_path.display()
            );
            return Ok(());
        }
    }
    fs::create_dir_all(&hooks_dir).context("failed to create git hooks directory")?;
    fs::write(&hook_path, content).context("failed to write git pre-commit hook")?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&hook_path)?.permissions();
        perms.set_mode(perms.mode() | 0o755);
        fs::set_permissions(&hook_path, perms).context("failed to chmod git pre-commit hook")?;
    }
    eprintln!("  Created {}", hook_path.display());
    Ok(())
}

fn configure_git_filter(cwd: &Path, dry_run: bool) -> Result<()> {
    if git_hooks_dir(cwd).is_none() {
        return Ok(());
    }
    if dry_run {
        eprintln!("  git config filter.snapper.clean \"snapper-fmt --native --stdin-filepath %f\"");
        eprintln!("  git config filter.snapper.smudge cat");
        return Ok(());
    }
    let clean = Command::new("git")
        .args([
            "config",
            "filter.snapper.clean",
            "snapper-fmt --native --stdin-filepath %f",
        ])
        .current_dir(cwd)
        .status();
    let smudge = Command::new("git")
        .args(["config", "filter.snapper.smudge", "cat"])
        .current_dir(cwd)
        .status();
    match (clean, smudge) {
        (Ok(c), Ok(s)) if c.success() && s.success() => {
            eprintln!("  Configured git filter.snapper.clean/smudge");
        }
        _ => {
            eprintln!("  git config filter.snapper.* failed, skipping");
        }
    }
    Ok(())
}

/// Generate Apheleia elisp snippet.
fn generate_apheleia(formats: &[&str]) -> String {
    let mut s = String::from(";; Add to your Emacs config:\n(with-eval-after-load 'apheleia\n");
    s.push_str("  (push '(snapper . (\"snapper\" \"--native\")) apheleia-formatters)\n");
    for fmt in formats {
        let mode = match *fmt {
            "org" => "org-mode",
            "latex" => "latex-mode",
            "markdown" => "markdown-mode",
            _ => continue,
        };
        s.push_str(&format!(
            "  (push '({mode} . snapper) apheleia-mode-alist)\n"
        ));
    }
    s.push_str(")\n");
    s
}

/// Run the init command.
pub fn run_init(dry_run: bool) -> Result<()> {
    let cwd = std::env::current_dir()?;
    let formats = detect_formats(&cwd);

    eprintln!(
        "Detected formats: {}",
        if formats.is_empty() {
            "none (will use plaintext defaults)".to_string()
        } else {
            formats.join(", ")
        }
    );

    // .snapperrc.toml
    let config_content = generate_config(&formats);
    let config_path = cwd.join(".snapperrc.toml");
    if config_path.exists() {
        eprintln!("  .snapperrc.toml already exists, skipping");
    } else if dry_run {
        eprintln!("\n--- .snapperrc.toml ---");
        eprint!("{config_content}");
    } else {
        fs::write(&config_path, &config_content).context("failed to write .snapperrc.toml")?;
        eprintln!("  Created .snapperrc.toml");
    }

    // .gitattributes
    if !formats.is_empty() {
        let ga_content = generate_gitattributes(&formats);
        let ga_path = cwd.join(".gitattributes");
        if dry_run {
            eprintln!("\n--- .gitattributes (append) ---");
            eprint!("{ga_content}");
        } else if ga_path.exists() {
            let existing = fs::read_to_string(&ga_path)?;
            if !existing.contains("filter=snapper") {
                fs::write(&ga_path, format!("{existing}\n{ga_content}"))
                    .context("failed to append .gitattributes")?;
                eprintln!("  Appended to .gitattributes");
            } else {
                eprintln!("  .gitattributes already has snapper filter, skipping");
            }
        } else {
            fs::write(&ga_path, &ga_content).context("failed to write .gitattributes")?;
            eprintln!("  Created .gitattributes");
        }
    }

    write_precommit_hook(&cwd, dry_run)?;
    configure_git_filter(&cwd, dry_run)?;

    // Print pre-commit and Apheleia snippets
    eprintln!("\n{}", generate_precommit());
    eprintln!("{}", generate_apheleia(&formats));

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_config_with_org() {
        let config = generate_config(&["org"]);
        assert!(config.contains("format = \"org\""));
        assert!(config.contains("max_width = 0"));
        assert!(config.contains("# clause_breaks = false"));
    }

    #[test]
    fn generate_config_empty_defaults_to_plaintext() {
        let config = generate_config(&[]);
        assert!(config.contains("format = \"plaintext\""));
    }

    #[test]
    fn generate_config_includes_seven_code_languages() {
        let config = generate_config(&["markdown"]);
        // The seven seed languages required by the [code] table.
        for lang in [
            "rust",
            "python",
            "toml",
            "lua",
            "lisp",
            "html",
            "javascript",
        ] {
            assert!(
                config.contains(&format!("[code.{lang}]")),
                "missing [code.{lang}] entry in init template",
            );
        }
        // Verify shape of one entry with all three fields.
        assert!(config.contains(r#"line_comment = "//""#));
        assert!(config.contains(r#"formatter = ["rustfmt", "--edition", "2024"]"#));
    }

    #[test]
    fn generate_gitattributes_multiple_formats() {
        let ga = generate_gitattributes(&["org", "latex", "markdown"]);
        assert!(ga.contains("*.org filter=snapper"));
        assert!(ga.contains("*.tex filter=snapper"));
        assert!(ga.contains("*.md filter=snapper"));
    }

    #[test]
    fn generate_gitattributes_empty() {
        let ga = generate_gitattributes(&[]);
        assert!(ga.contains("# snapper"));
        assert!(!ga.contains("filter=snapper"));
    }

    #[test]
    fn generate_precommit_hook_is_native_and_has_fmt_fallback() {
        let hook = generate_precommit_hook();
        assert!(hook.starts_with("#!/bin/sh"));
        assert!(hook.contains(HOOK_MARKER));
        assert!(hook.contains("--native"));
        assert!(
            hook.find("command -v snapper-fmt").unwrap()
                < hook.find("command -v snapper >/dev/null").unwrap(),
            "hook must prefer snapper-fmt over argv0 snapper"
        );
        assert!(hook.contains("--in-place"));
        assert!(hook.contains("filter.snapper.clean=cat"));
        assert!(hook.contains("*.org|*.tex|*.latex|*.md|*.markdown|*.rst|*.txt"));
    }
}
